datastore:
  image: busybox
  volumes:
      - /opt/datastore:/var/lib/mysql
  container_name: mysql-datastore
mysql:
  image: mysql:5.7.21
  environment:
    MYSQL_DATABASE: scraping_db
    MYSQL_USER: scraping_user
    MYSQL_PASSWORD: scraping_password
    MYSQL_ROOT_PASSWORD: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - datastore
  container_name: mysql-db